# path to the top-level directory containing the analysis results
data_root: run

# optionally the plots can have a "run name" prefix. If this is not defined the prefix will be "default"
run_name: nml

# path to the file containing the amplicon regions (not the primer sites, the actual amplicons)
amplicon_bed: ncov-qc_resende.bed

# path to the nCov reference genome
reference_genome: nCoV-2019.reference.fasta

# the naming convention for the bam files
# this can use the variables {data_root} (as above) and {sample}
# As per the example above, this will expand to run_200430/sampleA.sorted.bam for sampleA
bam_pattern: "{data_root}/{sample}.sorted.bam"

# the naming convention for the consensus sequences
consensus_pattern: "{data_root}/{sample}.consensus.fasta"

# when building a tree of the consensus genomes you can optionally include other sequences
# in the tree by providing a fasta file here
#tree_include_consensus: some_genomes_from_gisaid.fasta

# some plots can by annotated with external metadata. this
# file contains the metadata in simple tab-delimited format
# one column must be 'sample'
metadata: metadata.tsv

#
# set this flag to true to include lineage assignments with pangolin in the output plots
#
assign_lineages: true

#
# this flag should identify the sequencing platform used, valid options are:
# `illumina` or `oxford-nanopore`
#
platform: oxford-nanopore

#
# set the names of the negative controls
#
# negative_control_samples: [ "Negative1", "Negative2" ]
