#####################################
# Nextflow CI Test for NML Pipeline #
#####################################
name: ncov2019-artic-nf NML CI

on:
  pull_request: # Run on all pull requests
  push:
    branches: master
  schedule: # Run master on 5th of each month
    - cron: 0 6 5 * *
      branches: master

jobs:
  pipeline-test:
    name: ncov2019-artic-nf nanopore CI tests
    runs-on: ubuntu-latest

    steps:
    # Setup repo
    - uses: actions/checkout@v3
    - name: Create artifacts dir
      run: mkdir -p artifacts
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with: 
        python-version: 3.9

    # Add conda, mamba, and nextflow
    - name: Add Conda to system
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Nextflow and Mamba
      run: |
        conda update -n base -c defaults conda
        conda install -c conda-forge -c bioconda -c defaults mamba nextflow pandas
        rm -f /usr/share/miniconda/pkgs/cache/*.json # workaround for mamba-org/mamba#488
    - name: Nextflow Version
      run: | 
        nextflow -v
    # Check how repo looks incase there is an issue
    - name: List Files
      run: |
        ls -al ${{ github.workspace }}
    # Run Help Command
    - name: Pipeline Help CMD
      run: |
        nextflow run ./main.nf --help
    # Unzip fast5s to run
    - name: Unzip fast5 files
      run: |
        cd .github/nanopore/fast5_pass/barcode78/
        gunzip *.fast5.gz
        cd -

    # Run Pipelines
    - name: Run Nanopore Nanopolish with metadata
      run: bash .github/scripts/test_nml_nanopore_nanopolish.sh

    - name: Run Nanopore Nanopolish with no metadata
      run: bash .github/scripts/test_nml_nanopore_nanopolish.sh --no_metadata

    - name: Run Nanopore Medaka with metadata
      run: bash .github/scripts/test_nml_nanopore_medaka.sh

    - name: Run Nanopore Medaka flat
      run: bash .github/scripts/test_nml_nanopore_medaka_flat.sh

    - name: Done Pipelines
      run: echo "Done running pipelines"
